//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rövidítés.
        /// </summary>
        public static string Abbrev {
            get {
                return ResourceManager.GetString("Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segéd mértékegység.
        /// </summary>
        public static string AuxiliaryUnit {
            get {
                return ResourceManager.GetString("AuxiliaryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Számlázási cím.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Város.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ország.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiszállítva..
        /// </summary>
        public static string DD {
            get {
                return ResourceManager.GetString("DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alapértelmezett cikkár.
        /// </summary>
        public static string DefaultUnitPrice {
            get {
                return ResourceManager.GetString("DefaultUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Házszám.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depóban van. Kiszállításra vár..
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szállítási cím.
        /// </summary>
        public static string MailingAddress {
            get {
                return ResourceManager.GetString("MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikk.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikk típus.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eszköz.
        /// </summary>
        public static string MT_EQUIPMENT {
            get {
                return ResourceManager.GetString("MT_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék.
        /// </summary>
        public static string MT_PRODUCT {
            get {
                return ResourceManager.GetString("MT_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szolgáltatás.
        /// </summary>
        public static string MT_SERVICE {
            get {
                return ResourceManager.GetString("MT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiszállítás alatt áll. Célba tart..
        /// </summary>
        public static string OD {
            get {
                return ResourceManager.GetString("OD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelés tétel.
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyedi kulcs.
        /// </summary>
        public static string OrderKey {
            get {
                return ResourceManager.GetString("OrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az egyedi kulcs így néz ki: ABCD1234.
        /// </summary>
        public static string OrderKey_Error_Format {
            get {
                return ResourceManager.GetString("OrderKey_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelésszám.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Közterület neve.
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irányítószám.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár típus.
        /// </summary>
        public static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elsődeleges mértékegység.
        /// </summary>
        public static string PrimaryUnit {
            get {
                return ResourceManager.GetString("PrimaryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utca.
        /// </summary>
        public static string PS_STREET {
            get {
                return ResourceManager.GetString("PS_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elszámoló ár.
        /// </summary>
        public static string PT_ACCOUNTINGPRICE {
            get {
                return ResourceManager.GetString("PT_ACCOUNTINGPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készpénz.
        /// </summary>
        public static string PT_CASH {
            get {
                return ResourceManager.GetString("PT_CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankkártya.
        /// </summary>
        public static string PT_CREDITCARD {
            get {
                return ResourceManager.GetString("PT_CREDITCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista ár.
        /// </summary>
        public static string PT_LISTPRICE {
            get {
                return ResourceManager.GetString("PT_LISTPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beszerzési ár.
        /// </summary>
        public static string PT_PURCHASEPRICE {
            get {
                return ResourceManager.GetString("PT_PURCHASEPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eladási ár.
        /// </summary>
        public static string PT_SELLINGPRICE {
            get {
                return ResourceManager.GetString("PT_SELLINGPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átutalás.
        /// </summary>
        public static string PT_TRANSFER {
            get {
                return ResourceManager.GetString("PT_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csomag a futárnál. Depóba tart..
        /// </summary>
        public static string PU {
            get {
                return ResourceManager.GetString("PU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Közterület jellege.
        /// </summary>
        public static string PublicPlace {
            get {
                return ResourceManager.GetString("PublicPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI szorzó.
        /// </summary>
        public static string SIMultiplier {
            get {
                return ResourceManager.GetString("SIMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérjük jelentkezzen be, hogy ellenőrzni tudja csomagja állapotát..
        /// </summary>
        public static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csomag a feladónál. Futárra vár..
        /// </summary>
        public static string WfPU {
            get {
                return ResourceManager.GetString("WfPU", resourceCulture);
            }
        }

		public static string Register
		{
			get
			{
				return ResourceManager.GetString( "Register", resourceCulture );
			}
		}


		public static string Login
		{
			get
			{
				return ResourceManager.GetString( "Login", resourceCulture );
			}
		}


		public static string Welcome
		{
			get
			{
				return ResourceManager.GetString( "Welcome", resourceCulture );
			}
		}


		public static string Search
		{
			get
			{
				return ResourceManager.GetString( "Search", resourceCulture );
			}
		}


		public static string Create
		{
			get
			{
				return ResourceManager.GetString( "Create", resourceCulture );
			}
		}

		public static string Ok
		{
			get
			{
				return ResourceManager.GetString( "Ok", resourceCulture );
			}
		}

		public static string Edit
		{
			get
			{
				return ResourceManager.GetString( "Edit", resourceCulture );
			}
		}

		public static string Add
		{
			get
			{
				return ResourceManager.GetString( "Add", resourceCulture );
			}
		}
	}
}
